services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: pokeuser
      POSTGRES_PASSWORD: Ksnj237&Y87#T$474
      POSTGRES_DB: pokedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - poke

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - poke

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    image: django:latest
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      daphne -b 0.0.0.0 -p 8000 core.asgi:application
      "
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - DEBUG=False
      - HOST_IP=192.168.1.99
      - CSRF_TRUSTED_ORIGINS=https://poke.anwarhosen.xyz
      - DJANGO_SECRET_KEY=django-insecure-t2p2d0psa55mhz8j&v-6_y@%i(vageo$r0^*g=(3dr^yop1o)*
      - DATABASE_URL=postgres://pokeuser:Ksnj237&Y87#T$474@postgres:5432/pokedb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    expose:
      - "8000"
    networks:
      - poke

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
    depends_on:
      - django
    restart: unless-stopped
    networks:
      - poke

volumes:
  postgres_data:
    name: postgres_data
  redis_data:
    name: redis_data

networks:
  poke:
    name: poke
    driver: bridge
